# Prometheus Configuration for Production
# 🚀 Phase 16: Final Production Deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Trading Bot Application Metrics
  - job_name: 'trading-bot'
    static_configs:
      - targets: ['trading-bot:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Custom Trading Metrics
  - job_name: 'trading-metrics'
    static_configs:
      - targets: ['trading-bot:8000']
    scrape_interval: 5s
    metrics_path: '/api/metrics/trading'

  # Performance Metrics
  - job_name: 'performance-metrics'
    static_configs:
      - targets: ['trading-bot:8000']
    scrape_interval: 10s
    metrics_path: '/api/metrics/performance'

  # Security Metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['trading-bot:8000']
    scrape_interval: 60s
    metrics_path: '/api/metrics/security'